### ISSUE TITLE
Running client example code produces TypeError: task()!

### ISSUE THREAD

**Issue by knshetty** [jyio/geventreactor#1]
My development machine has Python: '2.7.3' and following python packages installed:
- geventreactor: '0.1.0'
- twisted: '13.0.0'
- gevent: '0.13.8'
- greenlet: '0.4.0'

When I run the Client example code(https://github.com/jyio/geventreactor#client) on my development machine as shown below. 

I get a TypeError...

Is there something that I am doing is wrong? Can you please help...

---

In [1]: import geventreactor; geventreactor.install()

In [2]: from twisted.internet import reactor

In [3]: from twisted.web.client import Agent

In [4]: from twisted.web.http_headers import Headers

In [5]: agent = Agent(reactor)

In [6]: d = agent.request(
   ...:     'GET',
   ...:     'http://example.com/',
   ...:     Headers({'User-Agent': ['Twisted Web Client Example']}),
   ...:     None)

In [7]: def cbResponse(ignored):
   ...:         print 'Response received'
   ...:     

In [8]: d.addCallback(cbResponse)
Out[8]: Deferred at 0xa07e44c>

In [9]: def cbShutdown(ignored):
   ...:         reactor.stop()
   ...:     

In [10]: d.addBoth(cbShutdown)
Out[10]: Deferred at 0xa07e44c>

In [11]: reactor.run()
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent-0.13.8-py2.7-linux-i686.egg/gevent/greenlet.py", line 390, in run
    result = self._run(_self.args, *_self.kwargs)
TypeError: task() takes no arguments (1 given)
Greenlet at 0x9ef266c: task('example.com')> failed with TypeError

**Comment by bitranch** [comment]
It looks like the definition of task() on line 150 in geventreactor/**init**.py should be task(_args, *_kwargs) instead.

**Comment by knshetty** [comment]
Great! Your suggestion works like a charm :)
Thanks for your help.

**Comment by koliyo** [comment]
This is still an issue, it should be fixed in the repository, we should not have to patch this locally. Please reopen this issue.

This is the code I'm trying to run in a gevent environment
http://autobahn.ws/python/wamp/programming.html#registering-procedures
